### ISSUE TITLE
Cannot get a value

### ISSUE THREAD

**Issue by ghotm** [retog/regexmap#1]
Hi,I ran into a problem when I was using it.

`Map test = new RegexMap();`
`test.put("id|account|type|trade","1");`
`test.put("post|get","2");`
`test.put("*","3")`
`System.out.println(test.get("asdd"));// null`
`System.out.println(test.get("123"));// null`

How to get it value for * ?
Sorry, my english may not be very good.
Thank you very much for your open source contribution.

**Comment by retog** [comment]
Sorry, just seeing this now: maybe you would mean `".*"` rather than `"*"`?
